/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "accel.h"
#include "lcd.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[32];
	AccelData_t accel;
	LcdInit();
	AccelInit();
	led_init();
	while(AccelWaitForChange()) {
		AccelRead(&accel);
		sprintf(str, "x= %d, y=%d      ", accel.x, accel.y);
		LcdPuts(LCD_LINE1, str);
		sprintf(str, "ACCEL %d      ", accel.z);
		LcdPuts(LCD_LINE2, str);
		DelayMs(500);

		if(accel.x > 3000){
				led_on3();
			}
		else
			led_off3();

		if(accel.x < -3000){
			led_on1();
		}
		else
			led_off1();
		if (accel.y > 3000){
			led_on2();
		}
		else
			led_off2();
		if (accel.y< -3000){
			led_on4();
			}
		else
			led_off4();
	}
}

