/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "rtc.h"
#include"i2c.h"
#include"timer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile extern int flag;
int main(void)
{
	RtcDate_t dt;
	char str1[50];
	char str2[50];
	dt.date =01;
	dt.year =25;
	dt.month =10;
	dt.weekday =2;
	RtcTime_t tm;
	tm.hr =21;
	tm.min =14;
	tm.sec =16;

	LcdInit();
	TimerInit(1000);
	RtcInit(&dt,&tm);
	while(1)
	{
		if(flag)
		{
			RtcGetDate(&dt);
			RtcGetTime(&tm);
			sprintf(str1,"%d-%d-%d-%d",dt.date,dt.month,dt.year,dt.weekday);
			sprintf(str2,"%d-%d-%d",tm.hr,tm.min,tm.sec);
			LcdPuts(0x80,str1);
			LcdPuts(0xC0,str2);
			flag=0;
		}
	}
}


