/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "led.h"
#include"systick.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern volatile uint32_t xTicks;

int main(void) {
	LedInit(LED_BLUE);
	// configure SysTick for periodic interrupt of 1ms.
	SysTick_Config(SystemCoreClock / 1000);
	// Toggle LED periodically using SysTick_Delay
	while(1) {
		LedToggle(15);
		SysTick_DelayMs(500);
	}
	return 0;
}





