/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************

*/
#include <stdint.h>
#include <stdio.h>
#include<string.h>
#include"lcd.h"
#include"uart.h"
#include"i2c.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[32];
	UartInit(9600);
	UartPuts("Enter strings...\r\n");
	while(1){
		UartGets(str);
		if(!(strncmp(str,'L1',2)))
		{
			DelayMs(100);
			LcdPuts(0x80,str);
		}

		else
		{
			DelayMs(100);
			LcdPuts(0xC0,str);
		}
	}
}
