/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "timer.h"
#include"extint.h"
#include"led.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


volatile extern int ext_flag;
int main(void) {
	int  duty =0;
	int count =1;
	TimerPwmInit();
	extint_init();
	while(1){
		if(ext_flag)
		{
			count++;
			if(count<=10)
			{
				duty +=10;
				TIM1->CCR1 = duty;
				DelayMs(40);

			}
			else{
				duty -=10;
				TIM1 -> CCR1 =duty;
				DelayMs(40);
				if(count ==20){
					count=0;
				}
			}
			ext_flag =0;
		}
	}

}



